name: TradingSystem
channels:
  - conda-forge 
  - defaults
dependencies:
  - python=3.10  
  - numpy
  - pandas
  - flask
  - requests
  - lxml
  - beautifulsoup4
  - yfinance
  - pip:
      - backtrader==1.9.78.123
      - bokeh==3.7.2
      - matplotlib==3.10.1
      - plotly==6.0.1
      - redis==5.2.1
      - gunicorn==23.0.0  
