DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS Stocks;
DROP TABLE IF EXISTS Trades;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS TradeHistory;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE Stocks (
  StockID INT PRIMARY KEY,
  Symbol VARCHAR(10) NOT NULL,
  Name VARCHAR(50) NOT NULL,
  
);

CREATE TABLE Trades (
  TradeID INT PRIMARY KEY,
  StockID INT NOT NULL,
  TradeDate DATE NOT NULL,
  TradeTime TIME NOT NULL,
  TradeType VARCHAR(10) NOT NULL CHECK (TradeType IN ('BUY', 'SELL')),
  Quantity INT NOT NULL,
  Price DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (StockID) REFERENCES Stocks(StockID)
);

CREATE TABLE Accounts (
  AccountID INT PRIMARY KEY,
  AccountHolder VARCHAR(50) NOT NULL
);

CREATE TABLE TradeHistory (
  TradeID INT NOT NULL,
  AccountID INT NOT NULL,
  FOREIGN KEY (TradeID) REFERENCES Trades(TradeID),
  FOREIGN KEY (AccountID) REFERENCES Accounts(AccountID),
  PRIMARY KEY (TradeID, AccountID)
);